* Алгоритмы
** DONE Генератор персонажей
*** DONE Вычисление очков умений
**** Общая характеристика
     Алгоритм предназначен для расчёта количества доступных для распределения очков умений уровня персонажа. Выполняется для каждого уровня персонажа.
**** Используемые данные
     Входными данными для данного алгоритма являются выбранный уровень, класс, модификатор интеллекта, очки, потраченные на умения для выбранного уровня.
**** Результаты выполнения
     Количество очков умений, доступных для распределения, является результатом выполнения алгоритма.
**** Математическое описание
     Пусть $М$ --- модификатор интеллекта, $С$ --- очки умений, доступные классу, $u_i$ --- очки, потраченные на развитие i-го умения на данном уровне, тогда количество доступных для распределения очков P вычисляется по формуле:
     $P = (M + C) - {\sum_{i=1}^{n} u_i}$
**** Логическое описание
     Пересчёт количества очков умений, доступных для распределения, происходит тогда, когда пользователь переназначает умения на данном уровне.
     Перерасчёт происходит по следующей схеме:
       Вычисляем модификатор интеллекта
       Прибавляем очки умений класса
       если очков умений меньше одного
         полные очки умений равны одному
       иначе
         полные очки умений равны сумме
       вычисляем использованные очки умений:
         сумма всех модификаторов умений на данном уровне (цикл)
       вычисляем доступные очки умений как разницу между полными очками и использованными
*** DONE Вычисление модификатора характеристики
**** Общая характеристика
     Алгоритм предназначен для расчёта модификатора характеристики.
**** Используемые данные
     В качестве входных данных алгоритм использует значение характеристики.
**** Результаты выполнения
     Результатом выполнения алгоритма является значение модификатора выбранной характеристики.
**** Математическое описание
     Алгоритм является сведением таблицы модификаторов\footnote{тут ссылка на книгу игрока} к формуле для вычисления.\\
     Пусть $V$ --- значение характеристики. Тогда вычисление её модификатора производится по формуле:
     $(V - 10) / 2$
**** Логическое описание
     При изменении значения какой-либо из способностей автоматически пересчитываются соответствующие параметры. В частности, при изменении значения интеллекта персонажа пересчитывается количество очков умений.
*** Вычисление уровня умения (defunct)
    Тут алгоритм вычисления уровня каждого умения
** DONE Аутентификация
*** Общая характеристика
    Алгоритм предназначен для аутентификации пользователя в системе.\\
    Входными данными для данного алгоритма являются две строки: тип провайдера и идентификатор пользователя на ресурсе провайдера.
*** Используемые данные
    Данный алгоритм использует две таблицы: таблицу пользователей и таблицу авторизационных данных.
*** Результаты выполнения
    Результатом выполнения является запись об аутентифицированном пользователе в системе и строка, которой пользователь может подтвердить факт аутентификации.
*** Логическое описание
    Получить входные данные.
    Если запись о пользователе существует в системе, то предоставить session_token
    Иначе
      Занести аутентификационные данные в базу
      Создать запись о пользователе, соответствующую аутентификационным данным
      Предоставить session_token
** Приглашение в игру/подтверждение приглашения (defunct)
*** Общая характеристика
    Алгоритм предназначен для участия в игре.
*** Используемые данные
    Данный алгоритм использует таблицы игр, пользователей и приглашений.
*** Результаты выполнения
    Запись об участии пользователя в игре.
*** Логическое описание
